[package]
name = "zoo_spree"
version = "0.1.0"
authors = ["Pat Goebel <putterson@gmail.com>"]

[dependencies]
sdl2 = "0.29"
gfx = "0.16"
gfx_core = "0.7"
gfx_window_sdl = "0.6"
log = "0.3"
env_logger = "*"
